name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
      - name: Build and Test
        env:
          JWT_SECRET_KEY: super-secret-key
          JWT_EXPIRATION_MINUTES: 10
          MONGODB_URI: mongodb://localhost:27017/
          MONGODB_DB_NAME: todo_api
        run: sbt -v +test
